### ISSUE TITLE
Data subdirectory is not created automatically

### ISSUE THREAD

**Issue by djmaze** [djmaze/dobs-volume-plugin#2]
Currently, the `data` subdirectory has to be manually created in the volume before first trying to mount it via this driver. This should either be done automatically in the driver or be documented.

**Comment by basz** [comment]
would the place to check and create a data directory in the volume if not exist be right after this call?

https://github.com/djmaze/dobs-volume-plugin/blob/master/dobs_driver.go#L194-L196

**Comment by djmaze** [comment]
Yeah, looks legit.

**Comment by djmaze** [comment]
Fixed in https://github.com/djmaze/dobs-volume-plugin/commit/b88ebdfc12c34593581a2ed5976723e82ce6bd0c
